"""Tests for the Abt-Buy loader.

These run against tiny committed fixtures under tests/fixtures/abt-buy/,
generated by tests/fixtures/make_fixtures.py. They cannot use the real CSVs:
data/ is gitignored, so a fresh clone has no datasets and a test that needed
one would fail for the wrong reason. The fixtures reproduce every shape the
real files were measured to contain -- a cp1252 byte, a thousands-comma
price, an empty price, a blank manufacturer, an id that collides across the
two sides, and a match graph with size-3, size-2 and singleton clusters.

The one test that does touch data/raw/ is marked and skips when absent.
"""

import collections
import csv
from pathlib import Path

import pytest

from dedup.data.abt_buy import (
    assign_entity_ids,
    load_abt_buy,
    load_pairs,
    load_products,
)
from dedup.schema import Record

FIXTURES = Path(__file__).parent / "fixtures" / "abt-buy"
REAL_DATA = Path(__file__).parent.parent / "data" / "raw" / "abt-buy"


@pytest.fixture
def records() -> dict[str, Record]:
    return {record.record_id: record for record in load_abt_buy(FIXTURES)}


# ---------------------------------------------------------------------------
# Encoding
# ---------------------------------------------------------------------------


def test_abt_csv_is_decoded_as_cp1252():
    # Abt.csv really is cp1252 on disk, so a default utf-8 read raises rather
    # than degrading. Assert the byte survives as the character it encodes,
    # which also catches a latin-1 style silent mojibake.
    assert b"\xae" in (FIXTURES / "Abt.csv").read_bytes()
    record = {r.record_id: r for r in load_products(FIXTURES)}["abt_buy:abt:10"]
    assert "®" in record.description


def test_utf8_read_of_the_fixture_would_fail():
    # Pins the reason the loader names an encoding at all. If this ever stops
    # raising, the fixture has lost the high byte and the test above is empty.
    with pytest.raises(UnicodeDecodeError):
        (FIXTURES / "Abt.csv").read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# record_id convention
# ---------------------------------------------------------------------------


def test_record_id_carries_the_side_so_colliding_raw_ids_stay_distinct():
    # Abt 10 and Buy 10 are unrelated products. schema.py's usual
    # f"{source}:{raw_id}" would map both to "abt_buy:10" and silently merge
    # them, so the loader puts the side in the middle.
    ids = {record.record_id for record in load_products(FIXTURES)}
    assert "abt_buy:abt:10" in ids
    assert "abt_buy:buy:10" in ids


def test_raw_attributes_preserve_side_and_source_id(records):
    record = records["abt_buy:buy:55"]
    assert record.raw_attributes == {"side": "buy", "raw_id": "55"}


# ---------------------------------------------------------------------------
# Price parsing
# ---------------------------------------------------------------------------


def test_price_strips_currency_symbol(records):
    assert records["abt_buy:abt:10"].price == 399.00


def test_price_strips_thousands_comma(records):
    # 97 of the 1008 populated prices in the real files look like this.
    assert records["abt_buy:abt:20"].price == 1299.00


def test_empty_price_becomes_none_not_nan(records):
    # The distinction schema.py now enforces: absent is None. pandas would
    # hand back NaN here, which propagates through numeric features silently.
    assert records["abt_buy:abt:30"].price is None


def test_unparseable_price_raises_rather_than_becoming_none(tmp_path):
    # Folding a malformed price into None would tell features/missingness.py
    # the source left the cell empty, which is a different fact.
    (tmp_path / "Abt.csv").write_text(
        '"id","name","description","price"\n1,"Widget","Desc","call for pricing"\n',
        encoding="cp1252",
    )
    with pytest.raises(ValueError, match="unparseable price"):
        load_products(tmp_path)


# ---------------------------------------------------------------------------
# The None vs "" convention across asymmetric sides
# ---------------------------------------------------------------------------


def test_abt_brand_is_none_because_the_column_is_absent(records):
    # Abt.csv has no manufacturer column at all. None means "the source did
    # not have this column populated".
    assert records["abt_buy:abt:10"].brand is None
    assert records["abt_buy:abt:20"].brand is None


def test_blank_buy_brand_is_empty_string_not_none(records):
    # Buy.csv has the column and leaves it blank on 6 of 1092 rows. "" means
    # "column present, value empty" -- a different fact from None, and the
    # one features/missingness.py keys off.
    assert records["abt_buy:buy:55"].brand == ""
    assert records["abt_buy:buy:10"].brand == "Canon"


def test_blank_buy_description_is_empty_string_not_none(records):
    assert records["abt_buy:buy:55"].description == ""


def test_brand_is_unusable_as_a_feature_on_this_benchmark(records):
    # Not a property of the loader so much as a fact about Abt-Buy worth
    # pinning: every pair spanning the two sides has a null brand on one
    # side, so brand equality is missing on every pair it would ever score.
    abt_side = [r for r in records.values() if r.raw_attributes["side"] == "abt"]
    assert all(record.brand is None for record in abt_side)


# ---------------------------------------------------------------------------
# Ground truth: pairs -> entity ids
# ---------------------------------------------------------------------------


def test_pairs_are_resolved_to_record_ids():
    assert ("abt_buy:abt:20", "abt_buy:buy:55") in load_pairs(FIXTURES)


def test_matched_records_share_an_entity_id(records):
    assert records["abt_buy:abt:20"].entity_id == records["abt_buy:buy:55"].entity_id


def test_transitive_matches_merge_into_one_entity(records):
    # Abt 10 matches Buy 98 and Buy 99 separately; the two Buy listings are
    # never paired with each other, so only the union-find joins them. This
    # is the connected-components step CLAUDE.md flags as a chaining hazard,
    # exercised deliberately rather than assumed harmless.
    entity = records["abt_buy:abt:10"].entity_id
    assert records["abt_buy:buy:98"].entity_id == entity
    assert records["abt_buy:buy:99"].entity_id == entity


def test_unmatched_record_gets_its_own_entity(records):
    # On a labeled benchmark an unmatched record is a known distinct product,
    # not an unknown one, so it is a singleton entity rather than None.
    singleton = records["abt_buy:abt:30"].entity_id
    assert singleton is not None
    assert [r for r in records.values() if r.entity_id == singleton] == [
        records["abt_buy:abt:30"]
    ]


def test_cluster_size_distribution_of_the_fixture(records):
    sizes = collections.Counter(
        collections.Counter(record.entity_id for record in records.values()).values()
    )
    assert sizes == {1: 2, 2: 1, 3: 1}


def test_entity_ids_are_stable_across_loads():
    # A shifting entity_id would silently reshuffle any cached entity-level
    # train/test split, which is the one split this project is allowed.
    first = {r.record_id: r.entity_id for r in load_abt_buy(FIXTURES)}
    second = {r.record_id: r.entity_id for r in load_abt_buy(FIXTURES)}
    assert first == second


def test_entity_ids_do_not_depend_on_input_order():
    records = load_products(FIXTURES)
    pairs = load_pairs(FIXTURES)
    forward = {r.record_id: r.entity_id for r in assign_entity_ids(records, pairs)}
    reversed_ = {
        r.record_id: r.entity_id
        for r in assign_entity_ids(list(reversed(records)), list(reversed(pairs)))
    }
    assert forward == reversed_


def test_pair_naming_an_unknown_record_raises():
    # A mapping row pointing at a record that is not in either CSV means the
    # files are out of sync; dropping it silently would understate recall.
    records = load_products(FIXTURES)
    with pytest.raises(KeyError, match="unknown record_id"):
        assign_entity_ids(records, [("abt_buy:abt:10", "abt_buy:buy:404")])


# ---------------------------------------------------------------------------
# File shape
# ---------------------------------------------------------------------------


def test_unexpected_columns_raise(tmp_path):
    # schema.py forbids extra fields, so a changed CSV would fail anyway --
    # but with a pydantic error about a field name rather than a message
    # naming the file whose shape moved.
    (tmp_path / "Abt.csv").write_text(
        '"id","title","description","price"\n1,"Widget","Desc","$1.00"\n', encoding="cp1252"
    )
    with pytest.raises(ValueError, match="Abt.csv: expected columns"):
        load_products(tmp_path)


# ---------------------------------------------------------------------------
# Integration against the real download, skipped when it is absent
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not (REAL_DATA / "Abt.csv").exists(),
    reason="benchmark not downloaded; see CLAUDE.md > Data",
)
def test_real_abt_buy_matches_its_measured_shape():
    records = load_abt_buy(REAL_DATA)
    sides = collections.Counter(record.raw_attributes["side"] for record in records)
    assert sides == {"abt": 1081, "buy": 1092}

    with (REAL_DATA / "abt_buy_perfectMapping.csv").open(encoding="ascii", newline="") as fh:
        assert sum(1 for _ in csv.DictReader(fh)) == 1097

    sizes = collections.Counter(
        collections.Counter(record.entity_id for record in records).values()
    )
    assert sizes == {2: 1055, 3: 21}, "ground-truth cluster shape moved; re-check chaining"

    abt = [r for r in records if r.raw_attributes["side"] == "abt"]
    assert all(record.brand is None for record in abt)
